### ISSUE TITLE
11月16日使用报错NoSuchElementException: Cannot locate an element using By.id: TANGRAM__PSP_4__userName

### ISSUE THREAD

**Issue by I321098** [songgeb/BDIndexSpider#18]
完整的bug log:
2018-11-16 21:33:05  [ AWT-EventQueue-0:0 ] - [ INFO ]  载入策略类： com.bdindex.model.TXTReader
   2018-11-16 21:33:05  [ AWT-EventQueue-0:0 ] - [ INFO ]  载入策略类： com.bdindex.model.CSVReader
   2018-11-16 21:33:05  [ AWT-EventQueue-0:10 ] - [ INFO ]  com.bdindex.model.TXTReader
   2018-11-16 21:33:06  [ SwingWorker-pool-2-thread-1:1150 ] - [ INFO ]  DriverFilePath: drivers/chromedriver.exe
   2018-11-16 21:33:06  [ SwingWorker-pool-2-thread-1:1150 ] - [ INFO ]  Driver folder exist
   2018-11-16 21:34:04  [ SwingWorker-pool-2-thread-1:58809 ] - [ ERROR ]  初始化失败
   org.openqa.selenium.TimeoutException: Expected condition failed: waiting for visibility of element located by By.id: TANGRAM__PSP_4__userName (tried for 3 second(s) with 500 milliseconds interval)
	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:113)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:283)
	at com.selenium.Wait.waitForElementVisible(Wait.java:82)
	at com.selenium.BDIndexAction.login(BDIndexAction.java:126)
	at com.bdindex.core.BDIndexCoreWorker.init(BDIndexCoreWorker.java:73)
	at com.bdindex.core.BDIndexCoreWorker.start(BDIndexCoreWorker.java:149)
	at com.bdindex.core.BDIndexCoreWorker.doInBackground(BDIndexCoreWorker.java:254)
	at com.bdindex.core.BDIndexCoreWorker.doInBackground(BDIndexCoreWorker.java:31)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.openqa.selenium.NoSuchElementException: Cannot locate an element using By.id: TANGRAM__PSP_4__userName
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'joekjzhou-PC1', ip: '10.17.93.34', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_171'
Driver info: driver.version: unknown
	at org.openqa.selenium.support.ui.ExpectedConditions.lambda$findElement$0(ExpectedConditions.java:896)
	at java.util.Optional.orElseThrow(Unknown Source)
	at org.openqa.selenium.support.ui.ExpectedConditions.findElement(ExpectedConditions.java:895)
	at org.openqa.selenium.support.ui.ExpectedConditions.access$000(ExpectedConditions.java:44)
	at org.openqa.selenium.support.ui.ExpectedConditions$7.apply(ExpectedConditions.java:206)
	at org.openqa.selenium.support.ui.ExpectedConditions$7.apply(ExpectedConditions.java:202)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:260)
	... 12 more

**Comment by songgeb** [comment]
@Emma-Fong @I321098 问题修复
